# Generated by Django 3.2.4 on 2022-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_mcart_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='cdate',
            field=models.DateField(),
        ),
    ]
